version: '2'
services:
  revealjs:
    build:
      context: docker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "35729:35729"
    volumes:
      - ./slides:/revealjs/slides:ro
